### PR TITLE
Fix a regression in OutputOnly after changes introduced in 3257953

### LINKED ISSUE #659: Regression in OutputOnly tasktype, probably due to the recent EvaluationService changes
```
2016-09-28 22:25:27,764 - ERROR [Worker,0] Worker failed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/Worker.py", line 121, in execute_job_group
    task_type.execute_job(job, self.file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/grading/TaskType.py", line 245, in execute_job
    self.evaluate(job, file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/grading/tasktypes/OutputOnly.py", line 111, in evaluate
    if "output_%s.txt" % job.testcase_codename not in job.files:
AttributeError: 'EvaluationJob' object has no attribute 'testcase_codename'
```

### PR DESCRIPTION
**Pull request by lucach**
Closes #659

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Thanks!
